/* ============================================================
   ASHARCHIVES DATABASE — BHALANI 3.0 / MUHS IMPORTANT TOPICS
   ============================================================
   Frequency mapping from source:
   **** = Tier 1 / highest frequency
   ***  = Tier 1 / very frequent
   **   = Tier 2 / frequent
   *    = Tier 3 / appeared at least once
   blank = Tier 3 / included in source but NOT confirmed as MUHS PYQ

   Notes are preserved rather than converting every unstarred topic into a
   confirmed MUHS PYQ. The source says unstarred topics may come from other
   university papers.
   ============================================================ */

const PYQS = [];

function frequencyToTier(freq){
    if(freq === "****" || freq === "***") return "Tier 1";
    if(freq === "**") return "Tier 2";
    return "Tier 3";
}

function addQ(subject,paper,section,topic,tier,type,question,frequency="",notes=""){
    PYQS.push({
        id: PYQS.length + 1,
        subject, paper, section, topic, tier, type, question, frequency, notes,
        confirmedMUHSPYQ: Boolean(frequency)
    });
}

function addBhalaniData(subject, paper, rows){
    rows.forEach(([section, topic, frequency, notes, type])=>{
        const tier = frequencyToTier(frequency || "");
        const qType = type || "Important";
        const question = topic;
        addQ(subject,paper,section,topic,tier,qType,question,frequency || "",notes || "");
    });
}

const ANATOMY_DATA = [
    ["Head, Neck & Face", "Scalp — layers, blood supply, nerve supply; clinical importance", "****", "Highest frequency indicated in source", "Important"],
    ["Head, Neck & Face", "Bell's palsy", "*", "", "Important"],
    ["Head, Neck & Face", "Dangerous area of face", "*", "", "Important"],
    ["Head, Neck & Face", "Orbicularis oculi and its antagonist", "", "", "Important"],
    ["Head, Neck & Face", "Lacrimal apparatus", "", "", "Important"],
    ["Head, Neck & Face", "Venous drainage of face", "", "", "Important"],
    ["Side of Neck", "Deep cervical fascia", "**", "", "Important"],
    ["Side of Neck", "Posterior triangle of neck", "", "", "Important"],
    ["Side of Neck", "Sternocleidomastoid — nerve supply, actions", "", "", "Important"],
    ["Anterior Triangles of Neck", "Carotid triangle & carotid sheath", "***", "", "Important"],
    ["Anterior Triangles of Neck", "Digastric triangle", "**", "", "Important"],
    ["Anterior Triangles of Neck", "Branches of external carotid artery", "*", "", "Important"],
    ["Anterior Triangles of Neck", "Anastomosis between internal & external carotid", "*", "", "Important"],
    ["Anterior Triangles of Neck", "Ansa cervicalis", "*", "", "Important"],
    ["Back of Neck", "Suboccipital triangle", "", "", "Important"],
    ["Parotid Gland", "External features", "****", "", "Important"],
    ["Parotid Gland", "Relations", "****", "", "Important"],
    ["Parotid Gland", "Histology", "****", "", "Important"],
    ["Parotid Gland", "Nerve supply", "****", "", "Important"],
    ["Parotid Gland", "Lymph drainage", "****", "", "Important"],
    ["Parotid Gland", "Applied anatomy", "****", "", "Important"],
    ["Temporal & Infratemporal Region", "Temporomandibular joint", "***", "", "Important"],
    ["Temporal & Infratemporal Region", "Muscles of mastication", "*", "", "Important"],
    ["Temporal & Infratemporal Region", "Otic ganglion", "*", "", "Important"],
    ["Temporal & Infratemporal Region", "Pterygoid muscles", "*", "", "Important"],
    ["Submandibular Region", "Submandibular salivary gland — applied", "*", "", "Important"],
    ["Submandibular Region", "Submandibular salivary gland — histology", "", "", "Important"],
    ["Submandibular Region", "Submandibular salivary gland — development", "", "", "Important"],
    ["Structures in the Neck", "Thyroid gland", "***", "", "Important"],
    ["Structures in the Neck", "Hypoglossal nerve", "*", "", "Important"],
    ["Structures in the Neck", "Cervical lymph nodes", "*", "", "Important"],
    ["Structures in the Neck", "Right & left subclavian artery", "**", "", "Important"],
    ["Cranial Cavity", "Cavernous sinus", "***", "", "Important"],
    ["Cranial Cavity", "Straight sinus", "*", "", "Important"],
    ["Cranial Cavity", "Falx cerebri", "", "", "Important"],
    ["Cranial Cavity", "Enumerate dural venous sinuses", "", "", "Important"],
    ["Contents of Orbit", "Extra-ocular muscles", "***", "", "Important"],
    ["Contents of Orbit", "Ciliary ganglion", "", "", "Important"],
    ["Contents of Orbit", "Oculomotor nerve", "**", "", "Important"],
    ["Mouth & Pharynx", "Palatine tonsil", "", "", "Important"],
    ["Mouth & Pharynx", "Muscles of pharynx", "", "", "Important"],
    ["Nose & Paranasal Sinuses", "Nasal septum", "***", "", "Important"],
    ["Nose & Paranasal Sinuses", "Lateral wall of nose", "***", "", "Important"],
    ["Nose & Paranasal Sinuses", "Maxillary air sinus", "", "", "Important"],
    ["Nose & Paranasal Sinuses", "Sphenoidal air sinus", "", "", "Important"],
    ["Larynx", "Cartilages", "", "", "Important"],
    ["Larynx", "Muscles & their actions", "", "", "Important"],
    ["Larynx", "Applied anatomy", "", "", "Important"],
    ["Larynx", "Movements of vocal cords", "**", "", "Important"],
    ["Tongue", "Muscles, nerve supply, development, histology, applied", "**", "", "Important"],
    ["Ear", "Middle ear — boundaries, contents, applied", "**", "", "Important"],
    ["Eyeball", "Layers of retina", "*", "", "Important"],
    ["Eyeball", "Development of retina", "", "", "Important"],
    ["Neuroanatomy — Spinal Cord", "T.S. at cervical level", "*", "", "Important"],
    ["Neuroanatomy — Spinal Cord", "Brown-Sequard syndrome", "*", "", "Important"],
    ["Neuroanatomy — Spinal Cord", "Pyramidal tracts", "", "", "Important"],
    ["Neuroanatomy — Spinal Cord", "Dorsal column pathway", "", "", "Important"],
    ["Cranial Nerves", "Mesencephalic nucleus of trigeminal nerve", "**", "", "Important"],
    ["Cranial Nerves", "Glossopharyngeal nerve", "*", "", "Important"],
    ["Cranial Nerves", "Facial nerve", "**", "", "Important"],
    ["Brainstem", "T.S. of medulla — pyramidal decussation", "***", "", "Important"],
    ["Brainstem", "T.S. of medulla — sensory decussation", "*", "", "Important"],
    ["Brainstem", "T.S. of medulla — mid-olivary nucleus", "*", "", "Important"],
    ["Brainstem", "T.S. of midbrain — superior colliculus", "", "", "Important"],
    ["Brainstem", "T.S. of midbrain — inferior colliculus", "", "", "Important"],
    ["Brainstem", "Facial colliculus", "*", "", "Important"],
    ["Brainstem", "Medial medullary syndrome", "**", "", "Important"],
    ["Brainstem", "T.S. of pons — facial colliculus level", "**", "", "Important"],
    ["Brainstem", "Midbrain — gross anatomy, blood supply", "", "", "Important"],
    ["Brainstem", "Pons — gross anatomy, internal structure, applied", "", "", "Important"],
    ["Cerebellum", "Inferior cerebellar peduncle", "***", "", "Important"],
    ["Cerebellum", "Cerebellum — lobes, connections, histology, blood supply", "**", "", "Important"],
    ["Fourth Ventricle", "Floor — draw & label, describe", "**", "", "Important"],
    ["Third Ventricle", "Third ventricle", "", "", "Important"],
    ["Third Ventricle", "Fornix of brain", "", "", "Important"],
    ["Third Ventricle", "Anterior horn of lateral ventricle", "", "", "Important"],
    ["Cerebrum, Diencephalon, Basal Nuclei & White Matter", "Corpus callosum", "***", "", "Important"],
    ["Cerebrum, Diencephalon, Basal Nuclei & White Matter", "Superolateral surface of cerebrum — sulci, gyri, functional areas, blood supply, applied anatomy", "", "", "Important"],
    ["Cerebrum, Diencephalon, Basal Nuclei & White Matter", "White matter of cerebrum — classification with examples; internal capsule", "**", "", "Important"],
    ["Cerebrum, Diencephalon, Basal Nuclei & White Matter", "Corpus striatum — components, connections, functions", "", "", "Important"],
    ["Cerebrum, Diencephalon, Basal Nuclei & White Matter", "Olivary group of nuclei", "", "", "Important"],
    ["Visual Pathway", "Visual pathway", "", "", "Important"],
    ["Auditory Pathway", "Auditory pathway", "", "", "Important"],
    ["Blood Supply of Brain & Spinal Cord", "Circle of Willis", "***", "", "Important"],
    ["Upper Limb — Pectoral Region", "Clavipectoral fascia", "**", "", "Important"],
    ["Upper Limb — Pectoral Region", "Mammary gland — blood supply, lymphatic drainage, applied anatomy", "****", "", "Important"],
    ["Upper Limb — Pectoral Region", "Serratus anterior", "*", "", "Important"],
    ["Upper Limb — Axilla", "Axillary group of lymph nodes", "*", "", "Important"],
    ["Upper Limb — Axilla", "Axillary artery", "*", "", "Important"],
    ["Upper Limb — Axilla", "Typical intercostal space", "*", "", "Important"],
    ["Upper Limb — Axilla", "Brachial plexus", "*", "", "Important"],
    ["Upper Limb — Axilla", "Erb's palsy & Erb's point", "**", "", "Important"],
    ["Upper Limb — Axilla", "Klumpke's palsy", "*", "", "Important"],
    ["Upper Limb — Scapular Region", "Quadrangular space", "*", "", "Important"],
    ["Upper Limb — Scapular Region", "Triangular space", "", "", "Important"],
    ["Upper Limb — Scapular Region", "Deltoid muscle", "*", "", "Important"],
    ["Upper Limb — Scapular Region", "Rotator cuff of shoulder joint", "**", "", "Important"],
    ["Upper Limb — Arm", "Cubital fossa", "***", "", "Important"],
    ["Upper Limb — Arm", "Biceps brachii", "*", "", "Important"],
    ["Upper Limb — Arm", "Radial nerve", "**", "", "Important"],
    ["Upper Limb — Arm", "Musculocutaneous nerve", "*", "", "Important"],
    ["Upper Limb — Arm", "Wrist drop", "**", "", "Important"],
    ["Upper Limb — Arm", "Median nerve", "*", "", "Important"],
    ["Upper Limb — Forearm & Hand", "Carpal tunnel syndrome", "**", "", "Important"],
    ["Upper Limb — Forearm & Hand", "Ulnar nerve", "*", "", "Important"],
    ["Upper Limb — Forearm & Hand", "Superficial palmar arch", "", "", "Important"],
    ["Upper Limb — Forearm & Hand", "Claw hand", "*", "", "Important"],
    ["Upper Limb — Forearm & Hand", "Anatomical snuff box", "*", "", "Important"],
    ["Upper Limb — Forearm & Hand", "Flexor retinaculum", "", "", "Important"],
    ["Upper Limb — Joints", "Sternoclavicular joint", "", "", "Important"],
    ["Upper Limb — Joints", "Pronation & supination", "**", "", "Important"],
    ["Upper Limb — Joints", "Shoulder joint — movements, relations, stabilizers, classification, blood supply, applied", "****", "", "Important"],
    ["Upper Limb — Joints", "Elbow joint", "", "", "Important"],
    ["Upper Limb — Spaces of Hand", "Mid-palmar space", "", "", "Important"],
    ["Thorax — Diaphragm", "Openings of diaphragm", "**", "", "Important"],
    ["Thorax — Walls", "Azygos vein", "**", "", "Important"],
    ["Thorax — Walls", "Typical intercostal nerve", "*", "", "Important"],
    ["Thorax — Lungs", "Bronchopulmonary segments", "***", "", "Important"],
    ["Thorax — Lungs", "Root of right & left lung", "*", "", "Important"],
    ["Thorax — Lungs", "Right lung — mediastinal relations, BPS, histology", "", "", "Important"],
    ["Thorax — Mediastinum", "Define mediastinum, classify", "*", "", "Important"],
    ["Thorax — Mediastinum", "Posterior & anterior mediastinum", "*", "", "Important"],
    ["Thorax — Mediastinum", "Superior mediastinum", "*", "", "Important"],
    ["Thorax — Mediastinum", "Development of arch of aorta", "", "", "Important"],
    ["Thorax — Heart & Pericardium", "Coronary sinus", "**", "", "Important"],
    ["Thorax — Heart & Pericardium", "Left coronary artery", "**", "", "Important"],
    ["Thorax — Heart & Pericardium", "Atrial septal defect", "**", "", "Important"],
    ["Thorax — Heart & Pericardium", "Interior of right atrium, development", "*", "", "Important"],
    ["Thorax — Heart & Pericardium", "Arterial & venous drainage of heart", "**", "", "Important"],
    ["Thorax — Heart & Pericardium", "Coronary blood circulation", "", "", "Important"],
    ["Thorax — Great Vessels", "Superior vena cava — formation, tributaries", "", "", "Important"],
    ["Thorax — Great Vessels", "Arch of aorta", "****", "", "Important"],
    ["Thorax — Great Vessels", "Thoracic duct", "***", "", "Important"],
    ["Thorax — Great Vessels", "Thoracic part of oesophagus", "", "", "Important"],
    ["Thorax — Great Vessels", "Thoracic part of trachea", "", "", "Important"],
    ["Thorax — Great Vessels", "Structures supplied by phrenic nerve", "", "", "Important"],
    ["Lower Limb — Front of Thigh", "Femoral triangle — femoral sheath", "***", "", "Important"],
    ["Lower Limb — Front of Thigh", "Femoral canal", "**", "", "Important"],
    ["Lower Limb — Front of Thigh", "Femoral hernia", "*", "", "Important"],
    ["Lower Limb — Front of Thigh", "Femoral artery", "*", "", "Important"],
    ["Lower Limb — Front of Thigh", "Sartorius", "**", "", "Important"],
    ["Lower Limb — Front of Thigh", "Adductor/Hunter/subsartorial canal", "***", "", "Important"],
    ["Lower Limb — Front of Thigh", "Femoral nerve", "", "", "Important"],
    ["Lower Limb — Front of Thigh", "Superficial inguinal lymph nodes", "*", "", "Important"],
    ["Lower Limb — Medial Thigh", "Obturator nerve", "*", "", "Important"],
    ["Lower Limb — Medial Thigh", "Adductor magnus", "*", "", "Important"],
    ["Lower Limb — Gluteal Region", "Gluteus medius", "", "", "Important"],
    ["Lower Limb — Gluteal Region", "Structures under cover of gluteus maximus", "*", "", "Important"],
    ["Lower Limb — Gluteal Region", "Trendelenburg test", "*", "", "Important"],
    ["Lower Limb — Popliteal Fossa", "Popliteal fossa — boundaries, contents, applied", "***", "", "Important"],
    ["Lower Limb — Popliteal Fossa", "Popliteal artery", "**", "", "Important"],
    ["Lower Limb — Popliteal Fossa", "Common peroneal nerve", "", "", "Important"],
    ["Lower Limb — Popliteal Fossa", "Foot drop", "*", "", "Important"],
    ["Lower Limb — Back of Thigh", "Sciatic nerve", "****", "", "Important"],
    ["Lower Limb — Back of Thigh", "Flexors of knee joint", "*", "", "Important"],
    ["Lower Limb — Back of Thigh", "Hamstring muscles", "", "", "Important"],
    ["Lower Limb — Leg & Dorsum of Foot", "Dorsalis pedis artery", "*", "", "Important"],
    ["Lower Limb — Leg & Dorsum of Foot", "Deep peroneal nerve", "", "", "Important"],
    ["Lower Limb — Back of Leg", "Popliteus muscle", "****", "", "Important"],
    ["Lower Limb — Back of Leg", "Soleus muscle", "*", "", "Important"],
    ["Lower Limb — Back of Leg", "Gastrocnemius muscle", "**", "", "Important"],
    ["Lower Limb — Back of Leg", "Tibialis posterior", "*", "", "Important"],
    ["Lower Limb — Venous Drainage", "Varicose veins", "**", "", "Important"],
    ["Lower Limb — Venous Drainage", "Long saphenous vein", "***", "", "Important"],
    ["Lower Limb — Venous Drainage", "Great saphenous vein", "*", "", "Important"],
    ["Lower Limb — Venous Drainage", "Venous drainage of lower limb", "**", "", "Important"],
    ["Lower Limb — Joints", "Inversion & eversion of foot", "***", "", "Important"],
    ["Lower Limb — Joints", "Knee joint", "**", "", "Important"],
    ["Lower Limb — Joints", "Housemaid's knee", "*", "", "Important"],
    ["Lower Limb — Joints", "Hip joint", "*", "", "Important"],
    ["Lower Limb — Joints", "Intra-articular surface of knee joint", "", "", "Important"],
    ["Lower Limb — Joints", "Ankle joint", "", "", "Important"],
    ["Lower Limb — Arches of Foot", "Medial longitudinal arch — factors maintaining", "***", "", "Important"],
    ["Lower Limb — Arches of Foot", "Lateral longitudinal arch", "***", "", "Important"],
    ["Abdomen & Pelvis — Sacral Canal", "Sacral canal", "", "", "Important"],
    ["Anterior Abdominal Wall", "Rectus sheath", "**", "", "Important"],
    ["Anterior Abdominal Wall", "Inguinal canal", "**", "", "Important"],
    ["Anterior Abdominal Wall", "Inguinal hernia", "", "", "Important"],
    ["Anterior Abdominal Wall", "Contents of spermatic cord", "*", "", "Important"],
    ["Anterior Abdominal Wall", "Structures passing through deep & superficial inguinal rings", "*", "", "Important"],
    ["Anterior Abdominal Wall", "Clinical importance of umbilicus", "*", "", "Important"],
    ["Anterior Abdominal Wall", "Caput medusae", "*", "", "Important"],
    ["Anterior Abdominal Wall", "Transpyloric plane", "", "", "Important"],
    ["Male Genital Organ", "Blood-testis barrier", "*", "", "Important"],
    ["Male Genital Organ", "Testis — gross, histology, development, descent, applied", "***", "", "Important"],
    ["Abdominal Cavity & Peritoneum", "Lesser omentum", "***", "", "Important"],
    ["Abdominal Cavity & Peritoneum", "Lesser sac", "", "", "Important"],
    ["Abdominal Cavity & Peritoneum", "Epiploic foramen", "*", "", "Important"],
    ["Oesophagus & Stomach", "Stomach bed", "***", "", "Important"],
    ["Oesophagus & Stomach", "Stomach — blood supply, histology, lymphatic, development, applied, relations", "****", "", "Important"],
    ["Intestine", "McBurney's point", "*", "", "Important"],
    ["Intestine", "Appendix", "***", "", "Important"],
    ["Intestine", "Meckel's diverticulum", "*", "", "Important"],
    ["Intestine", "Root of mesentery", "", "", "Important"],
    ["Intestine", "2nd part of duodenum", "***", "", "Important"],
    ["Large Blood Vessels of Gut", "Portocaval anastomosis", "**", "", "Important"],
    ["Large Blood Vessels of Gut", "Portosystemic anastomosis", "*", "", "Important"],
    ["Large Blood Vessels of Gut", "Portal vein — description, tributaries", "", "", "Important"],
    ["Extrahepatic Biliary Apparatus", "Gross, histology, applied", "*", "", "Important"],
    ["Extrahepatic Biliary Apparatus", "Gall bladder", "*", "", "Important"],
    ["Spleen, Pancreas & Liver", "Spleen — gross, histology, functions", "*", "", "Important"],
    ["Spleen, Pancreas & Liver", "Liver — ligaments, blood supply", "*", "", "Important"],
    ["Spleen, Pancreas & Liver", "Head of pancreas — development", "***", "", "Important"],
    ["Spleen, Pancreas & Liver", "Pancreas — full", "", "", "Important"],
    ["Kidney", "Kidney — relations, congenital anomalies", "**", "", "Important"],
    ["Kidney", "Ureters", "", "", "Important"],
    ["Suprarenal Gland", "Histology, development, blood supply, applied", "**", "", "Important"],
    ["Diaphragm", "Attachment, openings, blood & nerve supply, applied", "*", "", "Important"],
    ["Posterior Abdominal Wall", "Quadratus lumborum", "*", "", "Important"],
    ["Posterior Abdominal Wall", "Inferior vena cava — tributaries & development", "**", "", "Important"],
    ["Perineum", "Superficial perineal pouch", "*", "", "Important"],
    ["Perineum", "Ischiorectal fossa", "***", "", "Important"],
    ["Perineum", "Pudendal/Alcock's canal", "*", "", "Important"],
    ["Perineum", "Perineal body", "*", "", "Important"],
    ["Urinary Bladder & Urethra", "Urinary bladder — relations, interior, arterial/venous supply, ligaments", "**", "", "Important"],
    ["Urinary Bladder & Urethra", "Female urethra", "*", "", "Important"],
    ["Urinary Bladder & Urethra", "Male urethra", "*", "", "Important"],
    ["Male Reproductive Organ", "Prostate gland", "", "", "Important"],
    ["Male Reproductive Organ", "Vas deferens", "", "", "Important"],
    ["Female Reproductive Organ", "Tubectomy", "", "", "Important"],
    ["Female Reproductive Organ", "Uterus — supports, development & congenital anomalies, histology", "***", "", "Important"],
    ["Female Reproductive Organ", "Ovary — relations, blood supply, histology, development", "***", "", "Important"],
    ["Female Reproductive Organ", "Anatomical basis of contraception", "*", "", "Important"],
    ["Female Reproductive Organ", "Uterine tube — gross, development", "*", "", "Important"],
    ["Anal Canal & Rectum", "Anal canal — gross, interior, development, applied, blood supply", "***", "", "Important"],
    ["Walls of Pelvis", "Pelvic diaphragm", "", "", "Important"],
    ["Walls of Pelvis", "Internal iliac artery", "", "", "Important"],
    ["Walls of Pelvis", "Hysterosalpingography", "", "", "Important"],
    ["General Anatomy — Skeleton", "Blood supply of long bone", "*", "", "Important"],
    ["General Anatomy — Skeleton", "Sesamoid bone", "", "", "Important"],
    ["General Anatomy — Skeleton", "Epiphysis", "**", "", "Important"],
    ["General Anatomy — Joints", "Types of cartilaginous joints", "**", "", "Important"],
    ["General Anatomy — Joints", "Pivot joint", "", "", "Important"],
    ["General Anatomy — Joints", "Synovial joints", "", "", "Important"],
    ["General Anatomy — Joints", "Symphysis", "", "", "Important"],
    ["General Anatomy — Joints", "Sutures", "*", "", "Important"],
    ["General Anatomy — Genetics", "Barr body", "*", "", "Important"],
    ["General Anatomy — Genetics", "Karyotyping", "***", "", "Important"],
    ["General Anatomy — Genetics", "Klinefelter syndrome", "*", "", "Important"],
    ["General Anatomy — Genetics", "Turner syndrome", "", "", "Important"],
    ["General Anatomy — Genetics", "Lyon's hypothesis", "", "", "Important"],
    ["General Anatomy — Genetics", "X-linked recessive — pedigree characteristics", "", "", "Important"],
];

const PHYSIOLOGY_DATA = [
    ["General Physiology", "Homeostasis — definition", "**", "", "Important"],
    ["General Physiology", "Negative & positive feedback mechanism — compare", "", "", "Important"],
    ["General Physiology", "Various transport mechanisms across cell membrane", "*", "", "Important"],
    ["General Physiology", "Osmosis", "", "", "Important"],
    ["General Physiology", "Active transport", "*", "", "Important"],
    ["General Physiology", "Facilitated diffusion", "*", "", "Important"],
    ["General Physiology", "Na-K pump — importance", "", "", "Important"],
    ["General Physiology", "Resting membrane potential — ionic basis of RMP", "", "", "Important"],
    ["Nerve-Muscle — Action Potential", "Nerve action potential — draw & label; ionic basis, genesis, phases", "*", "", "Important"],
    ["Nerve-Muscle — Action Potential", "Well-labelled diagram of neuron", "", "", "Important"],
    ["Nerve-Muscle — Propagation", "Saltatory conduction", "*", "", "Important"],
    ["Nerve-Muscle — Propagation", "Properties of nerve fibres", "*", "", "Important"],
    ["Nerve-Muscle — Propagation", "Factors affecting nerve conduction velocity", "*", "", "Important"],
    ["Nerve-Muscle — Propagation", "Classification of nerve fibres", "", "", "Important"],
    ["Neuromuscular Transmission", "NMJ — draw & label; events at NMJ; clinical importance", "***", "", "Important"],
    ["Neuromuscular Transmission", "Myasthenia gravis — cause, treatment", "*", "", "Important"],
    ["Neuromuscular Transmission", "End-plate potential — genesis", "", "", "Important"],
    ["Excitation-Contraction Coupling", "Sarcomere", "**", "", "Important"],
    ["Excitation-Contraction Coupling", "Excitation-contraction coupling — role of calcium ions", "*", "", "Important"],
    ["Excitation-Contraction Coupling", "Sarcotubular system in skeletal muscle", "", "", "Important"],
    ["Skeletal Muscle", "Red and white muscle fibre — compare", "", "", "Important"],
    ["Skeletal Muscle", "Isotonic & isometric contraction — compare", "", "", "Important"],
    ["Skeletal Muscle", "Motor unit", "*", "", "Important"],
    ["Skeletal Muscle", "Refractory period", "", "", "Important"],
    ["Skeletal Muscle", "Factors regulating force of skeletal muscle contraction", "*", "", "Important"],
    ["Molecular Basis of Skeletal Muscle Contraction", "Sliding filament theory", "**", "", "Important"],
    ["Molecular Basis of Skeletal Muscle Contraction", "Rigor mortis", "", "", "Important"],
    ["Blood — RBC & Erythropoiesis", "Erythropoiesis — factors regulating, stages", "**", "", "Important"],
    ["Blood — RBC & Erythropoiesis", "Erythropoietin", "", "", "Important"],
    ["Anaemia & Polycythaemia", "Classify anaemias; describe iron deficiency anaemia", "*", "", "Important"],
    ["Anaemia & Polycythaemia", "Megaloblastic anaemia — treatment", "", "", "Important"],
    ["Anaemia & Polycythaemia", "Nutritional anaemia", "", "", "Important"],
    ["Blood — WBC", "Morphology, classification & functions of WBCs", "", "", "Important"],
    ["Blood — WBC", "Leucopoiesis — note", "", "", "Important"],
    ["Blood — WBC", "Life cycle of WBCs", "", "", "Important"],
    ["Blood — Coagulation", "Mechanism of blood coagulation", "***", "", "Important"],
    ["Blood — Coagulation", "Role of platelets in coagulation", "", "", "Important"],
    ["Blood — Coagulation", "Purpura & its causes", "", "", "Important"],
    ["Blood — Coagulation", "Define haemostasis", "", "", "Important"],
    ["Blood — Coagulation", "Mechanism of any one common anticoagulant used in clinical practice", "*", "", "Important"],
    ["Blood Groups", "Landsteiner’s law", "*", "", "Important"],
    ["Blood Groups", "Mismatched blood transfusion", "**", "", "Important"],
    ["Blood Groups", "Erythroblastosis foetalis", "*", "", "Important"],
    ["Blood Groups", "Rhesus factor", "", "", "Important"],
    ["Blood Groups", "Various blood grouping systems", "", "", "Important"],
    ["Immunity & Allergy", "Define & classify immunity; role of different T cells", "**", "", "Important"],
    ["Immunity & Allergy", "CD4 cells", "", "", "Important"],
    ["Immunity & Allergy", "Functions of T lymphocytes; relevance of HIV infection to T-lymphocyte function", "*", "", "Important"],
    ["Immunity & Allergy", "Primary & secondary immune response — role in vaccination", "*", "", "Important"],
    ["Immunity & Allergy", "Humoral immunity", "*", "", "Important"],
    ["CVS — Cardiac Muscle", "Properties of cardiac muscle — enumerate; why cannot be tetanised; ionic basis of autorhythmicity in SA node", "*", "", "Important"],
    ["CVS — Conduction", "Role of AV node & Purkinje fibres", "", "", "Important"],
    ["CVS — Conduction", "Origin & spread of cardiac impulse", "", "", "Important"],
    ["CVS — Conduction", "Heart block — types; explain AV nodal block", "**", "", "Important"],
    ["CVS — ECG", "Normal ECG — waves in lead II", "*", "", "Important"],
    ["CVS — ECG", "Normal ECG — description and recording", "**", "", "Important"],
    ["CVS — ECG", "Classify & describe leads used in ECG", "", "", "Important"],
    ["CVS — ECG", "Significance of P-R interval", "", "", "Important"],
    ["CVS — Cardiac Cycle", "Cardiac cycle — phases; pressure & volume changes", "***", "", "Important"],
    ["CVS — Cardiac Cycle", "Ejection fraction", "*", "", "Important"],
    ["CVS — Cardiac Cycle", "Heart sounds — note", "*", "", "Important"],
    ["CVS — Cardiac Output & Venous Return", "Cardiac output — definition, factors, measurement by Fick principle", "**", "", "Important"],
    ["CVS — Cardiac Output & Venous Return", "Factors controlling venous return", "*", "", "Important"],
    ["CVS — Cardiac Output & Venous Return", "Factors affecting stroke volume", "*", "", "Important"],
    ["CVS — Cardiac Output & Venous Return", "Cardiac index — definition", "", "", "Important"],
    ["CVS — Haemodynamics", "Poiseuille's law — significance", "", "", "Important"],
    ["CVS — Haemodynamics", "Peripheral resistance", "", "", "Important"],
    ["CVS — Short-term BP Regulation", "BP — definition, factors determining", "**", "", "Important"],
    ["CVS — Short-term BP Regulation", "Bainbridge reflex", "", "", "Important"],
    ["CVS — Short-term BP Regulation", "Baroreceptor mechanism", "**", "", "Important"],
    ["CVS — Short-term BP Regulation", "CNS ischaemic response", "*", "", "Important"],
    ["CVS — Short-term BP Regulation", "Mean BP — short-term mechanisms regulating BP", "**", "", "Important"],
    ["CVS — Long-term BP Regulation", "Renin-angiotensin mechanism", "*", "", "Important"],
    ["CVS — Long-term BP Regulation", "Role of JGA in regulation of BP", "*", "", "Important"],
    ["CVS — Long-term BP Regulation", "Long-term regulation of BP", "", "", "Important"],
    ["CVS — Coronary Circulation", "Peculiarities/features; factors regulating; applied physiology", "**", "", "Important"],
    ["CVS — Coronary Circulation", "Angina pectoris", "*", "", "Important"],
    ["CVS — Coronary Circulation", "Myocardial infarction — enumerate ECG changes", "*", "", "Important"],
    ["CVS — Coronary Circulation", "Cardiorespiratory changes during exercise", "*", "", "Important"],
    ["CVS — Circulatory Shock", "Define & classify shock; physiological basis of treatment", "*", "", "Important"],
    ["CVS — Circulatory Shock", "Stages of shock", "", "", "Important"],
    ["CVS — Circulatory Shock", "Hypovolaemic shock", "**", "", "Important"],
    ["Respiratory — Mechanics", "Lung compliance — factors affecting", "*", "", "Important"],
    ["Respiratory — Mechanics", "Surfactant — functions & applied RDS", "*", "", "Important"],
    ["Respiratory — Mechanics", "Dead space — method of measuring", "", "", "Important"],
    ["Respiratory — Mechanics", "Mechanics of respiration", "", "", "Important"],
    ["Respiratory — Mechanics", "Work of breathing", "**", "", "Important"],
    ["Respiratory — Mechanics", "Muscles of respiration", "", "", "Important"],
    ["Respiratory — Mechanics", "Obstructive lung disease — note", "*", "", "Important"],
    ["Respiratory — Lung Volumes", "Various lung volumes & capacities", "", "", "Important"],
    ["Respiratory — Lung Volumes", "Functional residual capacity", "", "", "Important"],
    ["Respiratory — Pulmonary Ventilation", "Positive pressure breathing — note", "", "", "Important"],
    ["Respiratory — Pulmonary Circulation", "Ventilation-perfusion ratio", "*", "", "Important"],
    ["Respiratory — Diffusion", "Respiratory membrane — layers and factors affecting gaseous exchange", "**", "", "Important"],
    ["Respiratory — Oxygen Transport", "Oxygen-haemoglobin curve — 2,3-BPG, p50, right/left shift", "***", "", "Important"],
    ["Respiratory — Oxygen Transport", "Bohr effect — note", "", "", "Important"],
    ["Respiratory — Oxygen Transport", "Hypoxia — define & classify", "", "", "Important"],
    ["Respiratory — Oxygen Transport", "Oxygen debt", "", "", "Important"],
    ["Respiratory — Oxygen Transport", "Oxygen transport — method", "***", "", "Important"],
    ["Respiratory — CO2 Transport", "CO2 transport", "***", "", "Important"],
    ["Respiratory — CO2 Transport", "Haldane effect", "", "", "Important"],
    ["Respiratory — Chemical Regulation", "Peripheral chemoreceptors", "*", "", "Important"],
    ["Respiratory — Chemical Regulation", "Tubuloglomerular feedback", "", "", "Important"],
    ["Respiratory — Chemical Regulation", "Respiratory acidosis & alkalosis", "*", "", "Important"],
    ["Respiratory — Chemical Regulation", "Chemical regulation of respiration", "**", "", "Important"],
    ["Respiratory — Chemical Regulation", "Kussmaul breathing — note", "*", "", "Important"],
    ["Respiratory — Neural Regulation", "Neural regulation of respiration", "**", "", "Important"],
    ["Respiratory — Neural Regulation", "Hering-Breuer reflex", "", "", "Important"],
    ["Respiratory — Neural Regulation", "Ondine's curse", "", "", "Important"],
    ["Respiratory — Neural Regulation", "Periodic breathing", "*", "", "Important"],
    ["Respiratory — Unusual Environment", "Acclimatization — definition", "*", "", "Important"],
    ["Respiratory — Unusual Environment", "Cardiorespiratory changes due to acclimatization at high altitude", "*", "", "Important"],
    ["Respiratory — Unusual Environment", "Acute mountain sickness", "", "", "Important"],
    ["Respiratory — Clinical", "Cyanosis", "", "", "Important"],
    ["Respiratory — Clinical", "Dyspnoea", "", "", "Important"],
    ["Respiratory — Clinical", "Asphyxia", "", "", "Important"],
    ["Exercise Physiology", "Cardiorespiratory changes during moderate exercise", "**", "", "Important"],
    ["Exercise Physiology", "VO2 max", "*", "", "Important"],
    ["Renal — Functional Anatomy", "Juxtaglomerular apparatus — functions; well-labelled diagram", "***", "", "Important"],
    ["Renal — Renal Flow", "GFR — definition, dynamics, factors, methods of measurement", "***", "", "Important"],
    ["Renal — Renal Flow", "Tubuloglomerular feedback & glomerulotubular balance", "", "", "Important"],
    ["Renal — Tubular Function", "PCT", "*", "", "Important"],
    ["Renal — Tubular Function", "Transport maximum", "*", "", "Important"],
    ["Renal — Tubular Function", "Glucose reabsorption in renal tubules", "**", "", "Important"],
    ["Renal — Tubular Function", "Inulin clearance", "", "", "Important"],
    ["Renal — Tubular Function", "Urea clearance", "", "", "Important"],
    ["Renal — Tubular Function", "Functions of DCT", "", "", "Important"],
    ["Renal — Urine Formation", "Counter-current mechanism", "**", "", "Important"],
    ["Renal — Urine Formation", "Handling of water and sodium by kidney", "", "", "Important"],
    ["Renal — Urine Formation", "Milieu intérieur; role of kidney in maintaining osmolarity of body fluid", "", "", "Important"],
    ["Renal — BP", "Role of JGA in regulation of BP", "*", "", "Important"],
    ["Renal — Acid Base", "Role of kidney in regulation of pH of body fluids", "", "", "Important"],
    ["Renal — Acid Base", "Blood buffers", "", "", "Important"],
    ["Renal — Micturition", "Micturition reflex", "*", "", "Important"],
    ["Renal — Micturition", "Innervation of urinary bladder", "", "", "Important"],
    ["Renal — Micturition", "Cystometrography", "", "", "Important"],
    ["Renal — Micturition", "Atonic bladder", "", "", "Important"],
    ["GIT — Salivary Glands", "Functions & composition of saliva", "*", "", "Important"],
    ["GIT — Salivary Glands", "Regulation of saliva secretion", "*", "", "Important"],
    ["GIT — Gastric Secretion", "Mechanism of HCl secretion", "****", "", "Important"],
    ["GIT — Gastric Secretion", "Functions of HCl", "", "", "Important"],
    ["GIT — Gastric Secretion", "Peptic ulcer — aetiology & treatment", "**", "", "Important"],
    ["GIT — Gastric Secretion", "Various gastrointestinal hormones", "*", "", "Important"],
    ["GIT — Gastric Secretion", "Composition of gastric secretion & regulation", "", "", "Important"],
    ["GIT — Exocrine Pancreas", "Functions, composition & regulation of pancreatic juice", "*", "", "Important"],
    ["GIT — Exocrine Pancreas", "CCK-PZ — note", "", "", "Important"],
    ["GIT — Liver", "Functions & composition of bile salts", "*", "", "Important"],
    ["GIT — Liver", "Regulation of biliary secretion", "", "", "Important"],
    ["GIT — Liver", "Emptying of gall bladder", "", "", "Important"],
    ["GIT — Liver", "Various functions of liver", "", "", "Important"],
    ["GIT — Motility", "Deglutition — definition, stages", "*", "", "Important"],
    ["GIT — Motility", "Movements of small intestine", "*", "", "Important"],
    ["GIT — Motility", "Movements of large intestine", "*", "", "Important"],
    ["GIT — Motility", "Defecation reflex", "**", "", "Important"],
    ["GIT — Motility", "Gastric emptying", "", "", "Important"],
    ["GIT — Motility", "Regulation of GI motility", "*", "", "Important"],
    ["GIT — Motility", "Deglutition reflex", "*", "", "Important"],
    ["GIT — Motility", "Peristaltic rush", "", "", "Important"],
    ["GIT — Motility", "Achalasia cardia", "", "", "Important"],
    ["Endocrine — Anterior Pituitary & Hypothalamus", "Growth hormone — mechanism, regulation, applied", "***", "", "Important"],
    ["Endocrine — Anterior Pituitary & Hypothalamus", "Dwarfism, gigantism, acromegaly", "*", "", "Important"],
    ["Endocrine — Anterior Pituitary & Hypothalamus", "Hormones of anterior pituitary — enumerate", "*", "", "Important"],
    ["Endocrine — Posterior Pituitary", "ADH — role, factors stimulating secretion, regulation", "*", "", "Important"],
    ["Endocrine — Posterior Pituitary", "Physiological basis of diabetes insipidus", "*", "", "Important"],
    ["Endocrine — Posterior Pituitary", "Functions of oxytocin", "", "", "Important"],
    ["Endocrine — Thyroid", "Thyroid hormone — synthesis, regulation, functions", "***", "", "Important"],
    ["Endocrine — Thyroid", "Cretinism", "*", "", "Important"],
    ["Endocrine — Thyroid", "Hyperthyroidism — note", "*", "", "Important"],
    ["Endocrine — Thyroid", "Physiological basis of antithyroid drugs", "", "", "Important"],
    ["Endocrine — Thyroid", "Differences between pituitary & thyroid dwarf", "", "", "Important"],
    ["Endocrine — Adrenal Cortex", "Hormones of adrenal cortex — enumerate", "", "", "Important"],
    ["Endocrine — Adrenal Cortex", "Aldosterone — functions, regulation", "", "", "Important"],
    ["Endocrine — Adrenal Cortex", "Cushing's syndrome", "*", "", "Important"],
    ["Endocrine — Adrenal Cortex", "Physiological actions of glucocorticoids", "", "", "Important"],
    ["Endocrine — Pancreas", "Diabetes mellitus vs diabetes insipidus", "**", "", "Important"],
    ["Endocrine — Pancreas", "Insulin — functions", "", "", "Important"],
    ["Endocrine — Pancreas", "Physiological basis of polyuria in diabetes", "", "", "Important"],
    ["Endocrine — Calcium", "Parathyroid hormone — function & regulation", "*", "", "Important"],
    ["Endocrine — Calcium", "Tetany — signs and treatment", "**", "", "Important"],
    ["Endocrine — Calcium", "Regulation of calcium level in body", "**", "", "Important"],
    ["Endocrine — Calcium", "Osteoporosis — note", "", "", "Important"],
    ["Endocrine — Calcium", "Rickets — note", "", "", "Important"],
    ["Reproductive — Male", "Spermatogenesis — stages, hormonal regulation", "***", "", "Important"],
    ["Reproductive — Male", "Actions of testosterone", "", "", "Important"],
    ["Reproductive — Placenta", "Functions of placenta; hormones secreted by placenta", "", "", "Important"],
    ["Reproductive — Female", "Ovulation — definition, mechanism, indicators", "*", "", "Important"],
    ["Reproductive — Female", "Contraception methods; oral contraceptives — action", "**", "", "Important"],
    ["Reproductive — Female", "Menstrual cycle — phases and hormonal regulation", "**", "", "Important"],
    ["Reproductive — Female", "Cyclic changes in uterus during reproductive life", "", "", "Important"],
    ["Reproductive — Parturition & Lactation", "Parturition — role of oxytocin", "", "", "Important"],
    ["Reproductive — Parturition & Lactation", "Physiology of lactation", "", "", "Important"],
    ["CNS — Synapse", "Properties of synapse", "*", "", "Important"],
    ["CNS — Synapse", "Presynaptic inhibition — advantage", "*", "", "Important"],
    ["CNS — Synapse", "Synaptic transmission", "", "", "Important"],
    ["CNS — Synapse", "Occlusion & subliminal fringe", "", "", "Important"],
    ["CNS — Sensory Receptors", "Types of sensory receptors — enumerate", "*", "", "Important"],
    ["CNS — Sensory Receptors", "Properties of receptors", "*", "", "Important"],
    ["CNS — Somatosensory Pathways", "Ascending tracts — enumerate", "*", "", "Important"],
    ["CNS — Somatosensory Pathways", "Dorsal column-medial lemniscal pathway — origin, course, termination, applied", "**", "", "Important"],
    ["CNS — Somatosensory Pathways", "Functions of tract of Goll & Burdach", "", "", "Important"],
    ["CNS — Muscle Spindle", "Muscle spindle — draw, label, functions", "*", "", "Important"],
    ["CNS — Muscle Spindle", "Stretch reflex and role in maintaining muscle tone", "*", "", "Important"],
    ["CNS — Pain & Temperature", "Fast vs slow pain — compare", "*", "", "Important"],
    ["CNS — Pain & Temperature", "Pain transmission through neospinothalamic pathway", "", "", "Important"],
    ["CNS — Pain & Temperature", "Descending pain-inhibiting system", "", "", "Important"],
    ["CNS — Pain & Temperature", "Different types of pain; referred pain — examples", "***", "", "Important"],
    ["CNS — Pain & Temperature", "Basis of phantom limb", "*", "", "Important"],
    ["CNS — Pain & Temperature", "Analgesia system of brain", "", "", "Important"],
    ["CNS — Pain & Temperature", "Thalamic syndrome", "", "", "Important"],
    ["CNS — Pyramidal Tract", "Pyramidal tract — origin, course, termination, applied", "**", "", "Important"],
    ["CNS — Pyramidal Tract", "Upper motor neuron lesion — note", "", "", "Important"],
    ["CNS — Pyramidal Tract", "UMN vs LMN lesion — differentiate", "*", "", "Important"],
    ["CNS — Motor Reflexes", "Stretch reflex arc — draw & label", "", "", "Important"],
    ["CNS — Motor Reflexes", "Classify reflexes", "", "", "Important"],
    ["CNS — Tone & Posture", "Tone of muscle — definition", "", "", "Important"],
    ["CNS — Tone & Posture", "Spinal and supraspinal regulation of tone", "", "", "Important"],
    ["CNS — Tone & Posture", "Decerebrate rigidity", "", "", "Important"],
    ["CNS — Cerebellum", "Functions & connections; cerebellar ataxia", "*", "", "Important"],
    ["CNS — Basal Ganglia", "Functions & connections; Parkinson disease", "*", "", "Important"],
    ["CNS — Hypothalamus", "Functions", "*", "", "Important"],
    ["CNS — EEG", "EEG — note; waves", "", "", "Important"],
    ["CNS — Sleep", "REM & NREM sleep", "*", "", "Important"],
    ["CNS — Learning & Memory", "Wernicke area", "", "", "Important"],
    ["CNS — Learning & Memory", "Aphasia — definition; sensory vs motor aphasia", "*", "", "Important"],
    ["CNS — Learning & Memory", "Alzheimer's disease", "", "", "Important"],
    ["CNS — Learning & Memory", "Memory — definition, classification, mechanisms", "*", "", "Important"],
    ["Special Senses — Taste & Smell", "Taste bud", "", "", "Important"],
    ["Special Senses — Taste & Smell", "Pathway of taste sensation", "*", "", "Important"],
    ["Special Senses — Taste & Smell", "Neural pathway for smell sensation", "*", "", "Important"],
    ["Special Senses — Eye", "Accommodation — reflex pathway", "***", "", "Important"],
    ["Special Senses — Eye", "Presbyopia — note", "", "", "Important"],
    ["Special Senses — Eye", "Errors of refraction — myopia, astigmatism", "", "", "Important"],
    ["Special Senses — Eye", "Argyll Robertson pupil — basis", "", "", "Important"],
    ["Special Senses — Retina", "Dark adaptation — curve, significance", "**", "", "Important"],
    ["Special Senses — Retina", "Photochemistry of vision", "", "", "Important"],
    ["Special Senses — Retina", "Colour vision", "", "", "Important"],
    ["Special Senses — Retina", "Theories of colour vision and colour blindness", "", "", "Important"],
    ["Special Senses — Hearing", "Structure of organ of Corti", "**", "", "Important"],
    ["Special Senses — Hearing", "Functions of middle ear", "**", "", "Important"],
    ["Special Senses — Hearing", "Conductive deafness — causes and tests", "*", "", "Important"],
    ["Special Senses — Hearing", "Attenuation — significance", "*", "", "Important"],
    ["Special Senses — Hearing", "Mechanism of hearing; pitch discrimination; impedance matching", "**", "", "Important"],
    ["Body Temperature Regulation", "Role of hypothalamus in temperature regulation", "***", "", "Important"],
    ["Body Temperature Regulation", "Shell temperature & core temperature", "*", "", "Important"],
    ["Body Temperature Regulation", "Heat loss mechanisms", "*", "", "Important"],
    ["Body Temperature Regulation", "Heat stroke — treatment; pyrexia", "*", "", "Important"],
    ["Body Temperature Regulation", "Body response to cold temperature", "**", "", "Important"],
    ["Body Temperature Regulation", "Different thermoreceptors", "", "", "Important"],
    ["Body Temperature Regulation", "Induced hypothermia — note", "", "", "Important"],
];

const BIOCHEMISTRY_DATA = [
    ["Amino Acids & Proteins", "Biologically important peptides", "**", "", "Important"],
    ["Amino Acids & Proteins", "Protein structure — secondary & tertiary", "**", "", "Important"],
    ["Amino Acids & Proteins", "Conjugation", "*", "", "Important"],
    ["Amino Acids & Proteins", "Important aminotransferases", "", "", "Important"],
    ["Amino Acids & Proteins", "Isoelectric pH", "", "", "Important"],
    ["Amino Acids & Proteins", "Functional & nutritional classification of proteins", "*", "", "Important"],
    ["Enzymes", "Diagnostic enzymes in cardiac diseases", "**", "", "Important"],
    ["Enzymes", "Isoenzymes — diagnostic importance with examples", "***", "", "Important"],
    ["Enzymes", "Coenzyme", "", "", "Important"],
    ["Enzymes", "Enzyme inhibition — competitive & non-competitive", "*", "", "Important"],
    ["Enzymes", "Activation energy — definition; ES complex diagram", "*", "", "Important"],
    ["Enzymes", "Classification of enzymes", "*", "", "Important"],
    ["Carbohydrates", "Glycosaminoglycans & significance", "****", "", "Important"],
    ["Carbohydrates", "Biomedical importance of cholesterol & hyaluronic acid", "", "", "Important"],
    ["Carbohydrates", "Reducing property of monosaccharides", "", "", "Important"],
    ["Lipids", "Classification of phospholipids with examples", "***", "", "Important"],
    ["Lipids", "Lipoproteins", "*", "", "Important"],
    ["Lipids", "Biologically important steroids", "", "", "Important"],
    ["Lipids", "Essential fatty acids — names and why essential", "", "", "Important"],
    ["Carbohydrate Metabolism", "HMP shunt — significance, regulation; why multifunctional", "****", "", "Important"],
    ["Carbohydrate Metabolism", "Glycogenesis & glycogenolysis — regulation", "*", "", "Important"],
    ["Carbohydrate Metabolism", "Glycogen storage diseases", "**", "", "Important"],
    ["Carbohydrate Metabolism", "Glycolytic pathway in RBCs", "*", "", "Important"],
    ["Carbohydrate Metabolism", "TCA cycle & energetics", "", "", "Important"],
    ["Carbohydrate Metabolism", "Gluconeogenesis", "*", "", "Important"],
    ["Carbohydrate Metabolism", "Rapoport-Luebering cycle — significance", "**", "", "Important"],
    ["Carbohydrate Metabolism", "Cori's cycle — importance", "", "", "Important"],
    ["Lipid Metabolism", "Beta oxidation of fatty acid — energetics", "**", "", "Important"],
    ["Lipid Metabolism", "Ketone bodies — enumerate, formation & fate; ketosis", "*", "", "Important"],
    ["Lipid Metabolism", "De novo synthesis of fatty acids", "*", "", "Important"],
    ["Lipid Metabolism", "Fatty liver", "**", "", "Important"],
    ["Lipid Metabolism", "Lipotropic factors", "*", "", "Important"],
    ["Cholesterol & Lipoproteins", "Cholesterol biosynthesis & regulation; functions", "***", "", "Important"],
    ["Cholesterol & Lipoproteins", "LDL & HDL — role in atherosclerosis", "*", "", "Important"],
    ["Cholesterol & Lipoproteins", "Formation & transport of chylomicrons", "*", "", "Important"],
    ["Polyunsaturated Fatty Acids", "Important functions", "", "", "Important"],
    ["Polyunsaturated Fatty Acids", "Enzyme deficient in Niemann-Pick's disease and clinical manifestations", "", "", "Important"],
    ["Amino Acid Metabolism", "Formation & fate of ammonia — urea cycle", "**", "", "Important"],
    ["Amino Acid Metabolism", "Transamination & transmethylation — brief", "**", "", "Important"],
    ["Amino Acid Metabolism", "Disorders of urea cycle", "", "", "Important"],
    ["Amino Acid Metabolism", "Deamination", "", "", "Important"],
    ["Amino Acid Metabolism", "Metabolism of glycine", "***", "", "Important"],
    ["Amino Acid Metabolism", "Formation of creatine", "", "", "Important"],
    ["Amino Acid Metabolism", "Metabolism of phenylalanine", "**", "", "Important"],
    ["Amino Acid Metabolism", "Metabolism of tyrosine", "**", "", "Important"],
    ["Amino Acid Metabolism", "Alkaptonuria & phenylketonuria — note", "**", "", "Important"],
    ["Plasma Proteins", "Immunoglobulins — types, diagram & features; explain any one in detail", "**", "", "Important"],
    ["Plasma Proteins", "Functions of plasma proteins", "*", "", "Important"],
    ["Biological Oxidation & ETC", "Oxidative phosphorylation; thermogenin", "*", "", "Important"],
    ["Biological Oxidation & ETC", "Uncouplers", "**", "", "Important"],
    ["Biological Oxidation & ETC", "ETC — describe, functions, inhibitors", "***", "", "Important"],
    ["Biological Oxidation & ETC", "Formation of acetyl CoA from pyruvate", "", "", "Important"],
    ["Biological Oxidation & ETC", "Malate-aspartate shuttle", "*", "", "Important"],
    ["Biological Oxidation & ETC", "Substrate-level phosphorylation", "*", "", "Important"],
    ["Heme Metabolism", "Heme synthesis & regulation; acute intermittent porphyria", "***", "", "Important"],
    ["Heme Metabolism", "Degradation of heme", "*", "", "Important"],
    ["Heme Metabolism", "Haemolytic jaundice", "", "", "Important"],
    ["Heme Metabolism", "Hemoglobinopathies", "*", "", "Important"],
    ["Heme Metabolism", "Biochemical basis of sickle cell anaemia", "", "", "Important"],
    ["Heme Metabolism", "Formation & fate of bilirubin", "*", "", "Important"],
    ["Heme Metabolism", "Methaemoglobin", "", "", "Important"],
    ["Liver Function Tests", "Role of various enzymes in LFT", "**", "", "Important"],
    ["Liver Function Tests", "Tests based on detoxification; excretory function", "*", "", "Important"],
    ["Kidney Function Tests", "Urea clearance test", "*", "", "Important"],
    ["Kidney Function Tests", "Creatinine clearance test", "*", "", "Important"],
    ["Acid-Base Balance", "Metabolic acidosis & alkalosis", "***", "", "Important"],
    ["Acid-Base Balance", "Buffer systems", "**", "", "Important"],
    ["Acid-Base Balance", "Role of kidney in maintaining acid-base balance", "*", "", "Important"],
    ["Acid-Base Balance", "Regulation of acid-base balance", "*", "", "Important"],
    ["Water & Electrolyte Balance", "Dehydration — note; primary & secondary dehydration", "**", "", "Important"],
    ["Water & Electrolyte Balance", "Water balance & regulation", "*", "", "Important"],
    ["Free Radicals & Antioxidants", "Antioxidant vitamins & enzymes", "*", "", "Important"],
    ["Free Radicals & Antioxidants", "Antioxidants", "*", "", "Important"],
    ["Free Radicals & Antioxidants", "Free radicals — name & explain", "", "", "Important"],
    ["Detoxification", "Xenobiotics — definition; phases of detoxification", "***", "", "Important"],
    ["Vitamins", "Vitamin A — sources, functions, deficiency; Wald visual cycle", "**", "", "Important"],
    ["Vitamins", "Vitamin D — sources, RDA, chemistry, functions, deficiency", "**", "", "Important"],
    ["Vitamins", "B-complex vitamins — enumerate and study all", "", "", "Important"],
    ["Vitamins", "Vitamin C", "**", "", "Important"],
    ["Digestion & Absorption", "Lactose intolerance", "", "", "Important"],
    ["Mineral Metabolism", "Iron — sources, role, absorption, disease manifestations, iron homeostasis", "**", "", "Important"],
    ["Mineral Metabolism", "Calcium — sources, functions, RDA, disease manifestations", "***", "", "Important"],
    ["Mineral Metabolism", "Factors influencing calcium absorption", "", "", "Important"],
    ["Mineral Metabolism", "Zinc", "*", "", "Important"],
    ["Mineral Metabolism", "Copper — Cu-containing enzymes", "*", "", "Important"],
    ["Mineral Metabolism", "Functions of phosphorus", "", "", "Important"],
    ["Mineral Metabolism", "Regulation of serum calcium levels", "**", "", "Important"],
    ["Energy Metabolism & Nutrition", "Protein-energy malnutrition — kwashiorkor & marasmus", "***", "", "Important"],
    ["Energy Metabolism & Nutrition", "Uses of dietary fibres", "*", "", "Important"],
    ["Energy Metabolism & Nutrition", "Basal metabolic rate", "**", "", "Important"],
    ["Nucleotide Metabolism", "Salvage pathway of purine synthesis", "**", "", "Important"],
    ["Nucleotide Metabolism", "Catabolism of purine", "*", "", "Important"],
    ["Nucleotide Metabolism", "Biologically important nucleotides", "**", "", "Important"],
    ["Nucleotide Metabolism", "Hyperuricaemia", "", "", "Important"],
    ["Nucleotide Metabolism", "Primary & secondary gout", "**", "", "Important"],
    ["DNA", "DNA replication — process and inhibitors", "**", "", "Important"],
    ["DNA", "Chargaff's rule", "*", "", "Important"],
    ["Transcription & Translation", "Different types of RNA — enumerate", "*", "", "Important"],
    ["Transcription & Translation", "tRNA — structure, diagram & functions", "", "", "Important"],
    ["Transcription & Translation", "Protein biosynthesis in prokaryotes — regulation & inhibitors", "*", "", "Important"],
    ["Transcription & Translation", "Ribosome — role in translation; antibiotics acting on ribosome", "*", "", "Important"],
    ["Transcription & Translation", "Reverse transcription — short note", "", "", "Important"],
    ["Mutation & Inheritance", "Genetic code — features", "***", "", "Important"],
    ["Mutation & Inheritance", "Lac operon", "*", "", "Important"],
    ["Mutation & Inheritance", "Point mutations", "", "", "Important"],
    ["Recombinant DNA Technology", "Applications of recombinant DNA technology — BAQ & SAQ", "**", "Source explicitly labels this section BAQ & SAQ", "BAQ/SAQ"],
    ["Recombinant DNA Technology", "What is recombinant DNA technology?", "", "Source explicitly labels this section BAQ & SAQ", "BAQ/SAQ"],
    ["Hormones", "Secondary messengers — cyclic AMP", "**", "", "Important"],
    ["Hormones", "Hormonal regulation of blood glucose", "*", "", "Important"],
    ["Hormones", "Mechanism of action of steroid hormones", "", "", "Important"],
    ["Hormones", "Mechanism of hydrophilic hormones", "", "", "Important"],
    ["Hormones", "Mechanism of Group II hormones", "", "", "Important"],
    ["Cancer", "Tumour markers — enumerate", "**", "", "Important"],
    ["Cancer", "Proto-oncogenes & oncogenes", "*", "", "Important"],
    ["Cancer", "Chemical carcinogens", "*", "", "Important"],
    ["Special Techniques", "Electrophoresis", "**", "", "Important"],
    ["Special Techniques", "Chromatography — types", "*", "", "Important"],
    ["Special Techniques", "Principle & use of flame photometer", "*", "", "Important"],
    ["Special Techniques", "Starvation", "***", "", "Important"],
    ["Special Techniques", "Radioactive isotopes — diagnostic & therapeutic use", "*", "", "Important"],
];

addBhalaniData("Anatomy", "Bhalani 3.0", ANATOMY_DATA);
addBhalaniData("Physiology", "Bhalani 3.0", PHYSIOLOGY_DATA);
addBhalaniData("Biochemistry", "Bhalani 3.0", BIOCHEMISTRY_DATA);

// ------------------------------------------------------------
// EXISTING SUBJECTS: keep your Pharmacology / Pathology /
// Microbiology / FMT addQ(...) entries below this line.
// ------------------------------------------------------------

const PHARMACOLOGY_DATA [
        "Antiepileptic drugs",
        "Antimalarial drugs / ACT",
        "Antitubercular drugs / MDR-TB",
        "Antihypertensive drugs",
        "Corticosteroids",
        "Oral hypoglycaemic drugs",
        "Insulin",
        "ACE inhibitors",
        "CHF treatment",
        "Adrenaline",
        "Beta blockers",
        "Anticholinesterases",
        "Organophosphate poisoning",
        "NSAIDs / Aspirin",
        "Antimicrobial selection",
        "Cephalosporins",
        "Penicillins",
        "Aminoglycosides",
        "Antipsychotics / antidepressants",
        "Opioids",
        "Peptic ulcer drugs",
        "Diuretics / Furosemide",
        "Iron preparations",
        "Statins",
        "Oxytocics",
        "Oral contraceptives"
    ],
    "Pathology": [
        "Necrosis",
        "Apoptosis",
        "Amyloidosis",
        "Oedema",
        "Thrombosis",
        "Embolism",
        "Acute inflammation",
        "Wound healing",
        "Neoplasia",
        "Metastasis",
        "Chemical carcinogenesis",
        "Anaemia",
        "Megaloblastic anaemia",
        "Leukemia",
        "Atherosclerosis",
        "Myocardial infarction",
        "Lung carcinoma",
        "Lobar pneumonia",
        "Gastric carcinoma",
        "Colorectal carcinoma",
        "Jaundice",
        "Alcoholic liver disease",
        "Glomerulonephritis",
        "Breast carcinoma",
        "Diabetes mellitus",
        "Meningitis",
        "Hodgkin lymphoma",
        "Osteosarcoma"
    ],
    "Microbiology": [
        "Sterilization / Autoclave",
        "Bacterial genetics / Gene transfer",
        "Tuberculosis",
        "Enteric fever",
        "Syphilis / Spirochetes",
        "Vibrio cholerae",
        "Chlamydia",
        "Clostridium",
        "Streptococcus",
        "UTI",
        "Meningitis",
        "PUO",
        "HIV",
        "Hepatitis B",
        "Influenza",
        "Antigen-antibody reactions",
        "Immunoglobulins",
        "Hypersensitivity",
        "Dermatophytes",
        "Opportunistic mycoses",
        "Malaria",
        "Leishmaniasis",
        "Ascariasis",
        "Hookworm",
        "Cestodes"
    ],
    "Forensic Medicine & Toxicology": [
        "Medical negligence",
        "Consent",
        "Dying declaration",
        "DNA fingerprinting",
        "Time since death",
        "Rigor mortis",
        "Hanging",
        "Strangulation",
        "Drowning",
        "Burns",
        "Skull fractures",
        "Firearm injuries",
        "Sexual assault examination",
        "Live birth / Hydrostatic test",
        "Snakebite",
        "Organophosphorus poisoning",
        "Opium poisoning",
        "Methanol poisoning",
        "Lead poisoning",
        "Aluminium phosphide poisoning",
        "Strychnine poisoning",
        "Barbiturate poisoning",
        "Duties of doctor in poisoning"
    ]
};

// Add the three new subjects to the high-yield dashboard.
ULTRA["Anatomy"] = [
    "Scalp clinical importance", "Parotid gland", "TMJ", "Carotid sheath", "Cavernous sinus",
    "Extra-ocular muscles", "Nasal septum", "Tongue", "Facial nerve", "Corpus callosum",
    "Circle of Willis", "Mammary gland", "Shoulder joint", "Cubital fossa", "Sciatic nerve",
    "Popliteal fossa", "Stomach", "Appendix", "Ischiorectal fossa", "Uterus", "Anal canal"
];

ULTRA["Physiology"] = [
    "Neuromuscular junction", "Blood coagulation", "Cardiac cycle", "Normal ECG", "Cardiac output",
    "Baroreceptor mechanism", "Hypovolaemic shock", "Oxygen transport", "CO2 transport",
    "GFR", "Counter-current mechanism", "HCl secretion", "Growth hormone", "Thyroid hormone",
    "Spermatogenesis", "Pain pathways", "Pyramidal tract", "Accommodation", "Dark adaptation",
    "Hypothalamus and temperature regulation"
];

ULTRA["Biochemistry"] = [
    "Glycosaminoglycans", "HMP shunt", "Isoenzymes", "Phospholipids", "Beta oxidation",
    "Cholesterol biosynthesis", "Urea cycle", "Glycine metabolism", "ETC", "Heme synthesis",
    "Metabolic acidosis and alkalosis", "Vitamin A", "Vitamin D", "Iron metabolism",
    "Protein-energy malnutrition", "Genetic code", "DNA replication", "Secondary messengers",
    "Tumour markers", "Electrophoresis", "Starvation"
];

// Source metadata used by the UI / future filters.
const DATASET_META = {
    source: "Bhalani 3.0 / Bhalani 2.pdf",
    reference: "Unique's Companion",
    note: "Source states it contains most MUHS previous-year questions. Unstarred topics may include other university papers and are not automatically confirmed MUHS PYQs.",
    embryologyHistologyNote: "Source recommends the old Bhalani for important Embryology and Histology topics."
};
let selectedAnswerType="LAQ";
let generatedPrompt="";
let lastAnswer="";

const SUBJECTS=["Anatomy","Physiology","Biochemistry","Pathology","Pharmacology","Microbiology","Forensic Medicine & Toxicology"];

function showPage(id,button){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));const page=document.getElementById(id);if(page)page.classList.add("active");document.querySelectorAll(".nav-btn").forEach(b=>b.classList.remove("active"));if(button)button.classList.add("active");window.scrollTo({top:0,behavior:"smooth"});if(id==="pyq")renderPYQs();if(id==="dashboard")renderDashboard()}
function selectAnswerType(el){document.querySelectorAll(".option").forEach(x=>x.classList.remove("selected"));el.classList.add("selected");selectedAnswerType=el.dataset.type}
function getSubjectRules(subject){const rules={
"Anatomy":["definition/identification where relevant","gross anatomy and relations","attachments, boundaries and contents where relevant","blood supply","nerve supply","lymphatic drainage","development/embryology where relevant","histology where relevant","applied/clinical anatomy","well-labelled diagrams and key relations"],
"Physiology":["definition and normal values where relevant","mechanism/sequence of events","ionic, neural or hormonal basis where relevant","regulation and feedback mechanisms","functions and physiological significance","important graphs/flowcharts/diagrams","clinical applications and physiological basis of disease","normal vs abnormal comparison where relevant","high-yield viva points"],
"Biochemistry":["definition/classification","site and pathway of metabolism","key reactions and rate-limiting enzymes","regulation","energy yield where relevant","clinical/medical significance","inborn errors or disorders where relevant","laboratory correlations","important vitamins/cofactors","flowcharts and pathway diagrams"],
"Pathology":["definition","classification","etiology/risk factors","pathogenesis","morphology/gross findings","microscopic findings","clinical features","complications","laboratory diagnosis","important differential tables"],
"Pharmacology":["definition/classification","prototype drugs","mechanism of action","pharmacological actions","pharmacokinetics where relevant","therapeutic uses with rationale","adverse effects","contraindications","drug interactions","important clinical pearls"],
"Microbiology":["classification","morphology","culture characteristics","pathogenesis","virulence factors","clinical manifestations","laboratory diagnosis","specimen collection","treatment/prevention where relevant","vaccines/prophylaxis where relevant"],
"Forensic Medicine & Toxicology":["definition","classification","mechanism/pathophysiology","clinical features","postmortem findings","medicolegal importance","diagnosis/investigation","management/treatment where relevant","important differentiating features","legal terminology where relevant"]};return rules[subject]||[]}
function buildPrompt(){const subject=document.getElementById("answerSubject").value;const paper=document.getElementById("answerPaper").value;const topic=document.getElementById("topicInput").value.trim();const depth=document.getElementById("answerDepth").value;const emphasis=document.getElementById("answerEmphasis").value;if(!topic){toast("Enter a topic or university question first.");document.getElementById("topicInput").focus();return}const rules=getSubjectRules(subject);generatedPrompt=`You are an expert Indian MBBS university examination tutor.\nASHARCHIVES — 2ND YEAR MBBS MUHS ANSWER ENGINE\nSUBJECT: ${subject}\nPAPER / SOURCE: ${paper}\nQUESTION TYPE: ${selectedAnswerType}\nTOPIC / QUESTION: ${topic}\nANSWER DEPTH: ${depth}\nEXTRA EMPHASIS: ${emphasis}\n\nOBJECTIVE: Generate a high-scoring undergraduate MBBS university examination answer. Do not invent facts. Prefer standard undergraduate textbook terminology. Make the answer easy to reproduce in an exam.\n\nSUBJECT-SPECIFIC STRUCTURE:\n${rules.map((x,i)=>(i+1)+". "+x).join("\n")}\n\nQuestion: ${topic}`;document.getElementById("generatedPrompt").value=generatedPrompt;document.getElementById("promptPanel").style.display="block";document.getElementById("promptPanel").scrollIntoView({behavior:"smooth",block:"start"});toast("University-level prompt generated.")}
async function copyGeneratedPrompt(){if(!generatedPrompt)buildPrompt();if(!generatedPrompt)return;try{await navigator.clipboard.writeText(generatedPrompt);toast("Prompt copied to clipboard.")}catch(e){document.getElementById("generatedPrompt").focus();document.execCommand("copy");toast("Prompt copied.")}}
async function openGemini(){if(!generatedPrompt)buildPrompt();if(!generatedPrompt)return;try{await navigator.clipboard.writeText(generatedPrompt);window.open("https://gemini.google.com/","_blank");toast("Prompt copied. Paste it into Gemini.")}catch(e){window.open("https://gemini.google.com/","_blank");toast("Gemini opened.")}}
function saveAPI(){const key=document.getElementById("apiKey").value.trim();if(!key){toast("Enter your Gemini API key.");return}localStorage.setItem("asharchives_gemini_key",key);localStorage.setItem("asharchives_gemini_model",document.getElementById("geminiModel").value);updateAPIStatus();toast("Gemini API key saved locally.")}
function clearAPI(){localStorage.removeItem("asharchives_gemini_key");document.getElementById("apiKey").value="";updateAPIStatus();toast("API key removed from browser.")}
function updateAPIStatus(){const key=localStorage.getItem("asharchives_gemini_key");const model=localStorage.getItem("asharchives_gemini_model")||"gemini-3.7-flash";const status=document.getElementById("apiStatus");if(key){document.getElementById("apiKey").value=key;document.getElementById("geminiModel").value=model;status.className="api-status ready";status.innerHTML=`✓ API key saved locally • Model: <strong>${escapeHTML(model)}</strong>`}else{status.className="api-status warning";status.innerHTML="No API key saved."}}
async function generateWithGemini(){if(!generatedPrompt)buildPrompt();if(!generatedPrompt)return;const key=localStorage.getItem("asharchives_gemini_key");if(!key){toast("Add your Gemini API key first.");return}const model=document.getElementById("geminiModel").value;const resultPanel=document.getElementById("resultPanel");const output=document.getElementById("answerOutput");const status=document.getElementById("generationStatus");resultPanel.classList.add("visible");resultPanel.scrollIntoView({behavior:"smooth",block:"start"});status.innerHTML='<span class="status-dot"></span>Generating...';output.innerHTML='<div style="padding:30px;text-align:center;color:#666">Generating answer...</div>';try{const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/interactions`,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":key},body:JSON.stringify({model,input:generatedPrompt,store:false,generation_config:{max_output_tokens:12000}})});const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||"Gemini request failed.");let text="";if(typeof data.output_text==="string")text=data.output_text;else if(Array.isArray(data.steps)){for(const step of data.steps){if(step.type==="model_output"&&Array.isArray(step.content)){for(const content of step.content){if(content.type==="text"&&typeof content.text==="string")text+=content.text}}}}if(!text)throw new Error("Gemini returned no text output.");lastAnswer=text;localStorage.setItem("asharchives_last_answer",text);output.innerHTML=markdownToHTML(text);status.innerHTML='<span class="status-dot"></span>Generation complete';saveHistory(document.getElementById("topicInput").value,document.getElementById("answerSubject").value,text)}catch(error){status.innerHTML='<span class="status-dot" style="background:#c92e2e"></span>Generation failed';output.innerHTML=`<div style="border:1px solid rgba(201,46,46,.3);background:#fff1f1;padding:20px;border-radius:12px;"><strong>Error:</strong> ${escapeHTML(error.message)}</div>`}}
function renderPYQs(){const search=document.getElementById("pyqSearch").value.toLowerCase().trim();const subject=document.getElementById("pyqSubject").value;const paper=document.getElementById("pyqPaper").value;const tier=document.getElementById("pyqTier").value;const type=document.getElementById("pyqType").value;const sort=document.getElementById("pyqSort").value;let filtered=PYQS.filter(q=>{const haystack=(q.question+" "+q.topic+" "+q.section+" "+q.subject).toLowerCase();return(!search||haystack.includes(search))&&(subject==="All"||q.subject===subject)&&(paper==="All"||q.paper===paper)&&(tier==="All"||q.tier===tier)&&(type==="All"||q.type===type)});const tierRank={"Tier 1":1,"Tier 2":2,"Tier 3":3};filtered.sort((a,b)=>{if(sort==="priority")return(tierRank[a.tier]||9)-(tierRank[b.tier]||9);if(sort==="subject")return a.subject.localeCompare(b.subject);return a.topic.localeCompare(b.topic)});document.getElementById("pyqSummary").innerHTML=`<div class="filter-chip">Showing <strong>${filtered.length}</strong> questions</div><div class="filter-chip">Tier 1: <strong>${filtered.filter(q=>q.tier==="Tier 1").length}</strong></div><div class="filter-chip">Anatomy: <strong>${filtered.filter(q=>q.subject==="Anatomy").length}</strong></div><div class="filter-chip">Physiology: <strong>${filtered.filter(q=>q.subject==="Physiology").length}</strong></div><div class="filter-chip">Biochemistry: <strong>${filtered.filter(q=>q.subject==="Biochemistry").length}</strong></div>`;const list=document.getElementById("pyqList");if(!filtered.length){list.innerHTML=`<div class="empty"><h3>No questions found</h3><button class="secondary" onclick="clearPYQFilters()">Clear filters</button></div>`;return}list.innerHTML=filtered.map(q=>`<article class="pyq-card"><div class="pyq-top"><div class="pyq-meta"><span class="badge ${q.tier==="Tier 1"?"tier1":q.tier==="Tier 2"?"tier2":"tier3"}">${escapeHTML(q.tier)}</span><span class="badge">${escapeHTML(q.subject)}</span><span class="badge">${escapeHTML(q.paper)}</span></div><span class="pyq-type">${escapeHTML(q.type||"Important")}</span></div><div class="pyq-question">${escapeHTML(q.question)}</div><div class="pyq-topic">${escapeHTML(q.section)} • ${escapeHTML(q.topic)}</div><div class="pyq-actions"><button class="small-btn dark" onclick="usePYQ(${q.id})">Use for Answer</button><button class="small-btn" onclick="copyQuestion(${q.id})">Copy</button></div></article>`).join("")}
function clearPYQFilters(){document.getElementById("pyqSearch").value="";document.getElementById("pyqSubject").value="All";document.getElementById("pyqPaper").value="All";document.getElementById("pyqTier").value="All";document.getElementById("pyqType").value="All";renderPYQs()}
function setSelectValue(id,value){const select=document.getElementById(id);if([...select.options].some(o=>o.value===value))select.value=value;else select.value="Not specified"}
function usePYQ(id){const q=PYQS.find(x=>x.id===id);if(!q)return;setSelectValue("answerSubject",q.subject);setSelectValue("answerPaper",q.paper);document.getElementById("topicInput").value=q.question;selectedAnswerType=["LAQ","SAQ/SN","Viva","Revision"].includes(q.type)?q.type:"LAQ";document.querySelectorAll(".option").forEach(x=>x.classList.toggle("selected",x.dataset.type===selectedAnswerType));showPage("home");buildPrompt();toast("PYQ loaded into Answer Builder.")}
async function copyQuestion(id){const q=PYQS.find(x=>x.id===id);if(!q)return;try{await navigator.clipboard.writeText(q.question);toast("Question copied.")}catch(e){toast("Clipboard unavailable.")}}
function openPYQSubjectModal(){document.getElementById("pyqModal").classList.add("open")}
function closePYQModal(){document.getElementById("pyqModal").classList.remove("open")}
function openSubjectPYQ(subject){closePYQModal();showPage("pyq");document.getElementById("pyqSubject").value=subject;renderPYQs()}
function randomQuestion(){const tier1=PYQS.filter(q=>q.tier==="Tier 1");const pool=tier1.length?tier1:PYQS;if(!pool.length){toast("No questions in database.");return}const q=pool[Math.floor(Math.random()*pool.length)];usePYQ(q.id);toast("Random high-yield question selected.")}
function renderDashboard(){const box=document.getElementById("subjectDashboard");box.innerHTML=SUBJECTS.map(subject=>{const total=PYQS.filter(q=>q.subject===subject).length;const tier1=PYQS.filter(q=>q.subject===subject&&q.tier==="Tier 1").length;const ultra=(ULTRA[subject]||[]).length;return`<div class="subject-card" onclick="openSubjectPYQ('${subject.replace(/'/g,"\\'")}')"><div class="badge tier1">${tier1} Tier 1</div><h3 style="margin-top:12px">${escapeHTML(subject)}</h3><p>${total} indexed questions • ${ultra} ultra-high-yield topics</p><div class="progress"><span style="width:${Math.min(100,(tier1/15)*100)}%"></span></div></div>`}).join("")}
function saveHistory(topic,subject,answer){let history=[];try{history=JSON.parse(localStorage.getItem("asharchives_history"))||[]}catch(e){}history.unshift({topic,subject,answer,date:new Date().toLocaleString()});localStorage.setItem("asharchives_history",JSON.stringify(history.slice(0,10)))}
function loadHistory(){let history=[];try{history=JSON.parse(localStorage.getItem("asharchives_history"))||[]}catch(e){}if(!history.length){toast("No generated answers yet.");return}const latest=history[0];setSelectValue("answerSubject",latest.subject);document.getElementById("topicInput").value=latest.topic;lastAnswer=latest.answer;document.getElementById("resultPanel").classList.add("visible");document.getElementById("answerOutput").innerHTML=markdownToHTML(latest.answer);showPage("home");toast("Latest answer restored.")}
async function copyAnswer(){if(!lastAnswer)return;try{await navigator.clipboard.writeText(lastAnswer);toast("Answer copied.")}catch(e){toast("Clipboard unavailable.")}}
function downloadAnswer(){if(!lastAnswer)return;const blob=new Blob([lastAnswer],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="ashArchives-answer.txt";a.click();URL.revokeObjectURL(url);toast("Answer downloaded.")}
function markdownToHTML(md){let text=escapeHTML(md);text=text.replace(/^### (.*)$/gm,"<h3>$1</h3>");text=text.replace(/^## (.*)$/gm,"<h2>$1</h2>");text=text.replace(/^# (.*)$/gm,"<h1>$1</h1>");text=text.replace(/\*\*(.*?)\*\*/g,"<strong>$1</strong>");text=text.replace(/^\- (.*)$/gm,"<li>$1</li>");text=text.replace(/(<li>.*<\/li>\n?)+/g,match=>"<ul>"+match+"</ul>");text=text.replace(/\n\n/g,"<br><br>");return text}
function escapeHTML(str){return String(str).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function toast(message){const el=document.getElementById("toast");el.textContent=message;el.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove("show"),2400)}
function focusBuilder(){document.getElementById("answerBuilder").scrollIntoView({behavior:"smooth",block:"start"});setTimeout(()=>document.getElementById("topicInput").focus(),500)}
document.addEventListener("DOMContentLoaded",()=>{document.getElementById("totalQuestions").textContent=PYQS.length;updateAPIStatus();renderPYQs();renderDashboard()});
document.getElementById("pyqModal").addEventListener("click",e=>{if(e.target.id==="pyqModal")closePYQModal()});
